import 'package:linkjoy/linkjoy_steamy/linkjoy_sister/linkjoy_io_sister.dart';

const Map<String, String> _viStrings = {
  'beauty_group_beauty': 'Làm đẹp',
  'beauty_group_filter': 'Bộ lọc',
  'beauty_group_makeup': 'Trang điểm',
  'beauty_group_sticker': 'Nhãn dán',
  'beauty_setting_saved_info': 'Đã lưu',
  'beauty_setting_reseted_info': 'Đặt lại',
  'beauty_setting_beauty': 'Làm đẹp',
  'beauty_setting_save': 'Lưu',
  'beauty_setting_reset': 'Đặt lại',
  'beauty_setting_join': 'Tham gia',
  'beauty_setting_leave': 'Rời đi',
  'beauty_setting_switch_camera': 'Chuyển',
  'beauty_effect_none': 'Không có',
  'beauty_effect_enable': 'Bật',
  'beauty_effect_disable': 'Tắt',
  'beauty_effect_reset': 'Đặt lại',
  'beauty_effect_smoothness': 'Mịn da',
  'beauty_effect_lightness': 'Trắng da',
  'beauty_effect_redness': 'Hồng hào',
  'beauty_effect_contrast_strength': 'Độ rõ',
  'beauty_effect_sharpness': 'Độ sắc',
  'beauty_effect_eye_pouch': 'Quầng\nthâm mắt',
  'beauty_effect_brighten_eye': 'Làm sáng\nmắt',
  'beauty_effect_whiten_teeth': 'Trắng\nrăng',
  'beauty_effect_nasolabial_fold': 'Nếp\ncười',
  'beauty_effect_temperature': 'Nhiệt độ',
  'beauty_effect_hue': 'Tông màu',
  'beauty_effect_saturation': 'Độ bão hòa',
  'beauty_effect_brightness': 'Độ sáng',
  'beauty_face_shape_face_contour': 'Thon gọn\nmặt',
  'beauty_face_shape_mandible': 'Khuôn\nV',
  'beauty_face_shape_chin': 'Cằm',
  'beauty_face_shape_cheek': 'Hàm dưới',
  'beauty_face_shape_cheekbone': 'Xương\ngò má',
  'beauty_face_shape_face_length': 'Dài\nkhuôn mặt',
  'beauty_face_shape_face_width': 'Rộng\nkhuôn mặt',
  'beauty_face_shape_fore_head': 'Đường\ntóc',
  'beauty_face_shape_head_scale': 'Kích thước\nđầu',
  'beauty_face_shape_nose_width': 'Thon\nmũi',
  'beauty_face_shape_nose_root': 'Gốc\nmũi',
  'beauty_face_shape_nose_bridge': 'Cầu\nmũi',
  'beauty_face_shape_nose_tip': 'Đầu\nmũi',
  'beauty_face_shape_nose_wing': 'Cánh\nmũi',
  'beauty_face_shape_nose_length': 'Dài\nmũi',
  'beauty_face_shape_nose_general': 'Tổng thể\nmũi',
  'beauty_face_shape_eye_scale': 'To\nmắt',
  'beauty_face_shape_eye_distance': 'Khoảng\ncách mắt',
  'beauty_face_shape_eye_lid': 'Mí mắt\ndưới',
  'beauty_face_shape_inner_corner': 'Góc\ntrong',
  'beauty_face_shape_outer_corner': 'Góc\nngoài',
  'beauty_face_shape_eye_position': 'Vị trí\nmắt',
  'beauty_face_shape_eye_pupils': 'Tròng đen',
  'beauty_face_shape_mouth_smile': 'Môi cười',
  'beauty_face_shape_mouth_lip': 'Dày\nmôi',
  'beauty_face_shape_mouth_scale': 'Kích thước\nmiệng',
  'beauty_face_shape_mouth_position': 'Rãnh môi',
  'beauty_face_shape_eyebrow_thickness': 'Dày\nlông mày',
  'beauty_face_shape_eyebrow_position': 'Nâng\nlông mày',
  'beauty_filter_serene': 'Yên tĩnh',
  'beauty_filter_urban': 'Đô thị',
  'beauty_filter_glow': 'Ánh sáng',
  'beauty_filter_gilt': 'Vàng kim',
  'beauty_filter_cream': 'Kem',
  'beauty_filter_latte': 'Latte',
  'beauty_filter_summer': 'Mùa hè',
  'beauty_filter_daily': 'Hàng ngày',
  'beauty_filter_gentleman': 'Quý ông',
  'beauty_filter_vanilla': 'Vani',
  'beauty_filter_bright': 'Tươi sáng',
  'beauty_filter_peach': 'Đào',
  'beauty_filter_ink': 'Mực',
  'beauty_filter_film': 'Phim ảnh',
  'beauty_filter_sunny': 'Nắng đẹp',
  'beauty_filter_comic': 'Truyện tranh',
  'beauty_filter_dreamy': 'Mơ màng',
  'beauty_filter_cotton': 'Bông',
  'beauty_filter_soda': 'Nước ngọt',
  'beauty_filter_moonlight': 'Ánh\ntrăng',
  'beauty_filter_white_tea': 'Trà\ntrắng',
  'beauty_filter_tranquil': 'Thanh bình',
  'beauty_filter_insta_style': 'Phong cách\nIns',
  'beauty_filter_street': 'Đường phố',
  'beauty_filter_puff': 'Bánh xốp',
  'beauty_filter_collection': 'Bộ sưu tập',
  'beauty_filter_salty': 'Vị mặn',
  'beauty_filter_texture': 'Kết cấu',
  'beauty_filter_colorful': 'Đa sắc',
  'beauty_filter_snow': 'Tuyết',
  'beauty_filter_blush': 'Đỏ má',
  'beauty_filter_nostalgia': 'Hoài niệm',
  'beauty_filter_caramel': 'Caramel',
  'beauty_filter_tipsy': 'Say nhẹ',
  'beauty_filter_lavender': 'Oải hương',
  'beauty_filter_rouge': 'Son đỏ',
  'beauty_filter_misty': 'Sương mù',
  'beauty_makeup_young': 'Trẻ trung',
  'beauty_makeup_mature': 'Trưởng thành',
  'beauty_makeup_aura': 'Khí chất',
  'beauty_makeup_natural': 'Tự nhiên',
  'beauty_makeup_graceful': 'Dịu dàng',
  'beauty_makeup_charm': 'Quyến rũ',
  'beauty_makeup_perky': 'Vui tươi',
  'beauty_makeup_maiden': 'Nữ tính',
  'beauty_makeup_insight': 'Sâu lắng',
  'beauty_makeup_misty': 'Sương khói',
  'beauty_sticker_christmas': 'Giáng sinh',
  'beauty_sticker_squid': 'Mực',
  'beauty_sticker_piggy': 'Heo con',
  'beauty_sticker_long_cat': 'Mèo dài',
  'beauty_sticker_hairhoop': 'Vòng tóc',
  'beauty_sticker_relax_time': 'Thư giãn',
  'beauty_sticker_cartoon_cat': 'Mèo hoạt hình',
  'beauty_sticker_butterfly': 'Bướm',
  'beauty_sticker_brush': 'Cọ trang điểm',
  'beauty_sticker_cyber_glass': 'Kính\nCyber',
  'beauty_sticker_neon_tiara': 'Vương miện\nNeon',
  'beauty_sticker_love_glass': 'Kính tình yêu',
};

const Map<String, String> _ptStrings = {
  'beauty_group_beauty': 'Beleza',
  'beauty_group_filter': 'Filtro',
  'beauty_group_makeup': 'Maquiagem',
  'beauty_group_sticker': 'Adesivo',
  'beauty_setting_saved_info': 'Salvo',
  'beauty_setting_reseted_info': 'Reiniciado',
  'beauty_setting_beauty': 'Beleza',
  'beauty_setting_save': 'Salvar',
  'beauty_setting_reset': 'Redefinir',
  'beauty_setting_join': 'Entrar',
  'beauty_setting_leave': 'Sair',
  'beauty_setting_switch_camera': 'Trocar',
  'beauty_effect_none': 'Nenhum',
  'beauty_effect_enable': 'Ativar',
  'beauty_effect_disable': 'Desativar',
  'beauty_effect_reset': 'Redefinir',
  'beauty_effect_smoothness': 'Suavizar',
  'beauty_effect_lightness': 'Clarear',
  'beauty_effect_redness': 'Rosado',
  'beauty_effect_contrast_strength': 'Clareza',
  'beauty_effect_sharpness': 'Nitidez',
  'beauty_effect_eye_pouch': 'Olheiras',
  'beauty_effect_brighten_eye': 'Iluminar\nOlhos',
  'beauty_effect_whiten_teeth': 'Clarear\nDentes',
  'beauty_effect_nasolabial_fold': 'Linhas\nde Riso',
  'beauty_effect_temperature': 'Temperatura',
  'beauty_effect_hue': 'Tom',
  'beauty_effect_saturation': 'Saturação',
  'beauty_effect_brightness': 'Brilho',
  'beauty_face_shape_face_contour': 'Afinar\nRosto',
  'beauty_face_shape_mandible': 'Rosto em\nV',
  'beauty_face_shape_chin': 'Queixo',
  'beauty_face_shape_cheek': 'Mandíbula',
  'beauty_face_shape_cheekbone': 'Maçãs do\nRosto',
  'beauty_face_shape_face_length': 'Comprimento\nRosto',
  'beauty_face_shape_face_width': 'Largura\nRosto',
  'beauty_face_shape_fore_head': 'Linha do\nCabelo',
  'beauty_face_shape_head_scale': 'Tamanho\nCabeça',
  'beauty_face_shape_nose_width': 'Afinar\nNariz',
  'beauty_face_shape_nose_root': 'Raiz do\nNariz',
  'beauty_face_shape_nose_bridge': 'Ponte do\nNariz',
  'beauty_face_shape_nose_tip': 'Ponta do\nNariz',
  'beauty_face_shape_nose_wing': 'Asas do\nNariz',
  'beauty_face_shape_nose_length': 'Comprimento\nNariz',
  'beauty_face_shape_nose_general': 'Nariz\nCompleto',
  'beauty_face_shape_eye_scale': 'Tamanho\nOlhos',
  'beauty_face_shape_eye_distance': 'Distância\nOlhos',
  'beauty_face_shape_eye_lid': 'Pálpebra\nInf.',
  'beauty_face_shape_inner_corner': 'Canto\nInterno',
  'beauty_face_shape_outer_corner': 'Canto\nExterno',
  'beauty_face_shape_eye_position': 'Posição\nOlhos',
  'beauty_face_shape_eye_pupils': 'Pupilas',
  'beauty_face_shape_mouth_smile': 'Sorriso',
  'beauty_face_shape_mouth_lip': 'Volume\nLábios',
  'beauty_face_shape_mouth_scale': 'Tamanho\nBoca',
  'beauty_face_shape_mouth_position': 'Filtro',
  'beauty_face_shape_eyebrow_thickness': 'Espessura\nSobrancelha',
  'beauty_face_shape_eyebrow_position': 'Levantar\nSobrancelha',
  'beauty_filter_serene': 'Sereno',
  'beauty_filter_urban': 'Urbano',
  'beauty_filter_glow': 'Brilhante',
  'beauty_filter_gilt': 'Dourado',
  'beauty_filter_cream': 'Creme',
  'beauty_filter_latte': 'Latte',
  'beauty_filter_summer': 'Verão',
  'beauty_filter_daily': 'Diário',
  'beauty_filter_gentleman': 'Cavalheiro',
  'beauty_filter_vanilla': 'Baunilha',
  'beauty_filter_bright': 'Claro',
  'beauty_filter_peach': 'Pêssego',
  'beauty_filter_ink': 'Tinta',
  'beauty_filter_film': 'Filme',
  'beauty_filter_sunny': 'Ensolarado',
  'beauty_filter_comic': 'Comic',
  'beauty_filter_dreamy': 'Sonhador',
  'beauty_filter_cotton': 'Algodão',
  'beauty_filter_soda': 'Refrigerante',
  'beauty_filter_moonlight': 'Luz da\nLua',
  'beauty_filter_white_tea': 'Chá\nBranco',
  'beauty_filter_tranquil': 'Tranquilo',
  'beauty_filter_insta_style': 'Estilo\nIns',
  'beauty_filter_street': 'Rua',
  'beauty_filter_puff': 'Sussuro',
  'beauty_filter_collection': 'Coleção',
  'beauty_filter_salty': 'Salgado',
  'beauty_filter_texture': 'Textura',
  'beauty_filter_colorful': 'Colorido',
  'beauty_filter_snow': 'Neve',
  'beauty_filter_blush': 'Blush',
  'beauty_filter_nostalgia': 'Nostalgia',
  'beauty_filter_caramel': 'Caramelo',
  'beauty_filter_tipsy': 'Bêbado',
  'beauty_filter_lavender': 'Lavanda',
  'beauty_filter_rouge': 'Vermelho',
  'beauty_filter_misty': 'Névoa',
  'beauty_makeup_young': 'Jovem',
  'beauty_makeup_mature': 'Maduro',
  'beauty_makeup_aura': 'Aura',
  'beauty_makeup_natural': 'Natural',
  'beauty_makeup_graceful': 'Elegante',
  'beauty_makeup_charm': 'Charme',
  'beauty_makeup_perky': 'Animado',
  'beauty_makeup_maiden': 'Donzela',
  'beauty_makeup_insight': 'Profundo',
  'beauty_makeup_misty': 'Névoa',
  'beauty_sticker_christmas': 'Natal',
  'beauty_sticker_squid': 'Lula',
  'beauty_sticker_piggy': 'Porquinho',
  'beauty_sticker_long_cat': 'Gato\nLongo',
  'beauty_sticker_hairhoop': 'Tiara',
  'beauty_sticker_relax_time': 'Relaxar',
  'beauty_sticker_cartoon_cat': 'Gato\nDesenho',
  'beauty_sticker_butterfly': 'Borboleta',
  'beauty_sticker_brush': 'Pincel',
  'beauty_sticker_cyber_glass': 'Óculos\nCyber',
  'beauty_sticker_neon_tiara': 'Tiara\nNéon',
  'beauty_sticker_love_glass': 'Óculos\nAmor',
};

const Map<String, String> _hiStrings = {
  'beauty_group_beauty': 'सौन्दर्य',
  'beauty_group_filter': 'फ़िल्टर',
  'beauty_group_makeup': 'मेकअप',
  'beauty_group_sticker': 'स्टिकर',
  'beauty_setting_saved_info': 'सेटिंग\nसहेजा',
  'beauty_setting_reseted_info': 'सेटिंग\nरीसेट',
  'beauty_setting_beauty': 'सौन्दर्य',
  'beauty_setting_save': 'सहेजें',
  'beauty_setting_reset': 'रीसेट',
  'beauty_setting_join': 'शामिल',
  'beauty_setting_leave': 'बाहर जाएँ',
  'beauty_setting_switch_camera': 'स्विच',
  'beauty_effect_none': 'कोई नहीं',
  'beauty_effect_enable': 'चालू',
  'beauty_effect_disable': 'बंद',
  'beauty_effect_reset': 'रीसेट',
  'beauty_effect_smoothness': 'स्मूथ',
  'beauty_effect_lightness': 'गोरापन',
  'beauty_effect_redness': 'लालिमा',
  'beauty_effect_contrast_strength': 'स्पष्टता',
  'beauty_effect_sharpness': 'शार्पनेस',
  'beauty_effect_eye_pouch': 'आँख\nकाला घेरा',
  'beauty_effect_brighten_eye': 'आँख\nचमक',
  'beauty_effect_whiten_teeth': 'दाँत\nसफेद',
  'beauty_effect_nasolabial_fold': 'स्माइल\nलाइन',
  'beauty_effect_temperature': 'टेम्परेचर',
  'beauty_effect_hue': 'रंग टोन',
  'beauty_effect_saturation': 'सैचुरेशन',
  'beauty_effect_brightness': 'ब्राइटनेस',
  'beauty_face_shape_face_contour': 'चेहरा\nपतला',
  'beauty_face_shape_mandible': 'V\nफेस',
  'beauty_face_shape_chin': 'ठुड्डी',
  'beauty_face_shape_cheek': 'जबड़ा',
  'beauty_face_shape_cheekbone': 'गाल\nहड्डी',
  'beauty_face_shape_face_length': 'चेहरा\nलंबा',
  'beauty_face_shape_face_width': 'चेहरा\nचौड़ा',
  'beauty_face_shape_fore_head': 'हेयरलाइन',
  'beauty_face_shape_head_scale': 'सिर\nसाइज',
  'beauty_face_shape_nose_width': 'नाक\nपतली',
  'beauty_face_shape_nose_root': 'नाक\nजड़',
  'beauty_face_shape_nose_bridge': 'नाक\nपुल',
  'beauty_face_shape_nose_tip': 'नाक\nसिरा',
  'beauty_face_shape_nose_wing': 'नाक\nपंख',
  'beauty_face_shape_nose_length': 'नाक\nलंबी',
  'beauty_face_shape_nose_general': 'नाक\nशेप',
  'beauty_face_shape_eye_scale': 'आँख\nबड़ी',
  'beauty_face_shape_eye_distance': 'आँख\nदूरी',
  'beauty_face_shape_eye_lid': 'निचली\nपलक',
  'beauty_face_shape_inner_corner': 'अंदरूनी\nकोना',
  'beauty_face_shape_outer_corner': 'बाहरी\nकोना',
  'beauty_face_shape_eye_position': 'आँख\nपोजीशन',
  'beauty_face_shape_eye_pupils': 'पुतली',
  'beauty_face_shape_mouth_smile': 'स्माइल\nलिप्स',
  'beauty_face_shape_mouth_lip': 'होंठ\nमोटे',
  'beauty_face_shape_mouth_scale': 'मुँह\nसाइज',
  'beauty_face_shape_mouth_position': 'फ़िलट्रम',
  'beauty_face_shape_eyebrow_thickness': 'भौंह\nमोटी',
  'beauty_face_shape_eyebrow_position': 'भौंह\nउठाएँ',
  'beauty_filter_serene': 'शांत',
  'beauty_filter_urban': 'शहरी',
  'beauty_filter_glow': 'चमकदार',
  'beauty_filter_gilt': 'सुनहरा',
  'beauty_filter_cream': 'क्रीम',
  'beauty_filter_latte': 'लेट्टे',
  'beauty_filter_summer': 'गर्मी',
  'beauty_filter_daily': 'रोजाना',
  'beauty_filter_gentleman': 'सज्जन',
  'beauty_filter_vanilla': 'वेनिला',
  'beauty_filter_bright': 'उज्ज्वल',
  'beauty_filter_peach': 'पीच',
  'beauty_filter_ink': 'स्याही',
  'beauty_filter_film': 'फिल्म',
  'beauty_filter_sunny': 'धूप',
  'beauty_filter_comic': 'कॉमिक',
  'beauty_filter_dreamy': 'स्वप्निल',
  'beauty_filter_cotton': 'कॉटन',
  'beauty_filter_soda': 'सोडा',
  'beauty_filter_moonlight': 'चंद्र\nप्रकाश',
  'beauty_filter_white_tea': 'सफ़ेद\nचाय',
  'beauty_filter_tranquil': 'सुकून',
  'beauty_filter_insta_style': 'इंस्टा\nस्टाइल',
  'beauty_filter_street': 'स्ट्रीट',
  'beauty_filter_puff': 'पफ',
  'beauty_filter_collection': 'संग्रह',
  'beauty_filter_salty': 'नमकीन',
  'beauty_filter_texture': 'बनावट',
  'beauty_filter_colorful': 'रंगीन',
  'beauty_filter_snow': 'बर्फ',
  'beauty_filter_blush': 'ब्लश',
  'beauty_filter_nostalgia': 'पुरानी यादें',
  'beauty_filter_caramel': 'कैरामेल',
  'beauty_filter_tipsy': 'मस्ती',
  'beauty_filter_lavender': 'लैवेंडर',
  'beauty_filter_rouge': 'लालिमा',
  'beauty_filter_misty': 'कोहरा',
  'beauty_makeup_young': 'यंग लुक',
  'beauty_makeup_mature': 'परिपक्व',
  'beauty_makeup_aura': 'औरा',
  'beauty_makeup_natural': 'प्राकृतिक',
  'beauty_makeup_graceful': 'सुंदर',
  'beauty_makeup_charm': 'आकर्षक',
  'beauty_makeup_perky': 'चुलबुला',
  'beauty_makeup_maiden': 'युवती',
  'beauty_makeup_insight': 'गहरा लुक',
  'beauty_makeup_misty': 'कोहरा लुक',
  'beauty_sticker_christmas': 'क्रिसमस',
  'beauty_sticker_squid': 'स्क्विड',
  'beauty_sticker_piggy': 'छोटा सूअर',
  'beauty_sticker_long_cat': 'लंबी बिल्ली',
  'beauty_sticker_hairhoop': 'हेयर हूप',
  'beauty_sticker_relax_time': 'आराम',
  'beauty_sticker_cartoon_cat': 'कार्टून बिल्ली',
  'beauty_sticker_butterfly': 'तितली',
  'beauty_sticker_brush': 'ब्रश',
  'beauty_sticker_cyber_glass': 'साइबर चश्मा',
  'beauty_sticker_neon_tiara': 'नियॉन मुकुट',
  'beauty_sticker_love_glass': 'लव चश्मा',
};

const Map<String, String> _esStrings = {
  'beauty_group_beauty': 'Belleza',
  'beauty_group_filter': 'Filtro',
  'beauty_group_makeup': 'Maquillaje',
  'beauty_group_sticker': 'Pegatina',
  'beauty_setting_saved_info': 'Guardado',
  'beauty_setting_reseted_info': 'Reiniciado',
  'beauty_setting_beauty': 'Belleza',
  'beauty_setting_save': 'Guardar',
  'beauty_setting_reset': 'Reiniciar',
  'beauty_setting_join': 'Unirse',
  'beauty_setting_leave': 'Salir',
  'beauty_setting_switch_camera': 'Cambiar',
  'beauty_effect_none': 'Ninguno',
  'beauty_effect_enable': 'Activar',
  'beauty_effect_disable': 'Desactivar',
  'beauty_effect_reset': 'Reiniciar',
  'beauty_effect_smoothness': 'Suavizar',
  'beauty_effect_lightness': 'Blanquear',
  'beauty_effect_redness': 'Sonrosado',
  'beauty_effect_contrast_strength': 'Claridad',
  'beauty_effect_sharpness': 'Nitidez',
  'beauty_effect_eye_pouch': 'Ojeras',
  'beauty_effect_brighten_eye': 'Iluminar\nOjos',
  'beauty_effect_whiten_teeth': 'Blanquear\nDientes',
  'beauty_effect_nasolabial_fold': 'Líneas\risa',
  'beauty_effect_temperature': 'Temperatura',
  'beauty_effect_hue': 'Tono',
  'beauty_effect_saturation': 'Saturación',
  'beauty_effect_brightness': 'Brillo',
  'beauty_face_shape_face_contour': 'Afinar\nCara',
  'beauty_face_shape_mandible': 'Cara en\nV',
  'beauty_face_shape_chin': 'Mentón',
  'beauty_face_shape_cheek': 'Mandíbula',
  'beauty_face_shape_cheekbone': 'Pómulos',
  'beauty_face_shape_face_length': 'Largo\nCara',
  'beauty_face_shape_face_width': 'Ancho\nCara',
  'beauty_face_shape_fore_head': 'Linea\nCabello',
  'beauty_face_shape_head_scale': 'Tamaño\nCabeza',
  'beauty_face_shape_nose_width': 'Afinar\Nariz',
  'beauty_face_shape_nose_root': 'Raíz\Nariz',
  'beauty_face_shape_nose_bridge': 'Puente\Nariz',
  'beauty_face_shape_nose_tip': 'Punta\Nariz',
  'beauty_face_shape_nose_wing': 'Aletas\Nariz',
  'beauty_face_shape_nose_length': 'Largo\Nariz',
  'beauty_face_shape_nose_general': 'Nariz\nCompleta',
  'beauty_face_shape_eye_scale': 'Tamaño\nOjos',
  'beauty_face_shape_eye_distance': 'Distancia\nOjos',
  'beauty_face_shape_eye_lid': 'Párpado\nInf.',
  'beauty_face_shape_inner_corner': 'Rincón\nInt.',
  'beauty_face_shape_outer_corner': 'Rincón\nExt.',
  'beauty_face_shape_eye_position': 'Posición\nOjos',
  'beauty_face_shape_eye_pupils': 'Pupilas',
  'beauty_face_shape_mouth_smile': 'Sonrisa',
  'beauty_face_shape_mouth_lip': 'Relleno\nLabios',
  'beauty_face_shape_mouth_scale': 'Tamaño\nBoca',
  'beauty_face_shape_mouth_position': 'Filtro',
  'beauty_face_shape_eyebrow_thickness': 'Grosor\nCejas',
  'beauty_face_shape_eyebrow_position': 'Levantar\nCejas',
  'beauty_filter_serene': 'Sereno',
  'beauty_filter_urban': 'Urbano',
  'beauty_filter_glow': 'Brillante',
  'beauty_filter_gilt': 'Dorado',
  'beauty_filter_cream': 'Crema',
  'beauty_filter_latte': 'Latte',
  'beauty_filter_summer': 'Verano',
  'beauty_filter_daily': 'Diario',
  'beauty_filter_gentleman': 'Caballero',
  'beauty_filter_vanilla': 'Vainilla',
  'beauty_filter_bright': 'Brillante',
  'beauty_filter_peach': 'Melocotón',
  'beauty_filter_ink': 'Tinta',
  'beauty_filter_film': 'Película',
  'beauty_filter_sunny': 'Soleado',
  'beauty_filter_comic': 'Comic',
  'beauty_filter_dreamy': 'Soñador',
  'beauty_filter_cotton': 'Algodón',
  'beauty_filter_soda': 'Soda',
  'beauty_filter_moonlight': 'Luz de\nLuna',
  'beauty_filter_white_tea': 'Té\nBlanco',
  'beauty_filter_tranquil': 'Tranquilo',
  'beauty_filter_insta_style': 'Estilo\nIns',
  'beauty_filter_street': 'Callejero',
  'beauty_filter_puff': 'Suspiro',
  'beauty_filter_collection': 'Colección',
  'beauty_filter_salty': 'Salado',
  'beauty_filter_texture': 'Textura',
  'beauty_filter_colorful': 'Colorido',
  'beauty_filter_snow': 'Nieve',
  'beauty_filter_blush': 'Rubor',
  'beauty_filter_nostalgia': 'Nostalgia',
  'beauty_filter_caramel': 'Caramelo',
  'beauty_filter_tipsy': 'Ebrio',
  'beauty_filter_lavender': 'Lavanda',
  'beauty_filter_rouge': 'Rojo',
  'beauty_filter_misty': 'Neblina',
  'beauty_makeup_young': 'Joven',
  'beauty_makeup_mature': 'Maduro',
  'beauty_makeup_aura': 'Aura',
  'beauty_makeup_natural': 'Natural',
  'beauty_makeup_graceful': 'Elegante',
  'beauty_makeup_charm': 'Encanto',
  'beauty_makeup_perky': 'Animado',
  'beauty_makeup_maiden': 'Doncella',
  'beauty_makeup_insight': 'Profundo',
  'beauty_makeup_misty': 'Neblina',
  'beauty_sticker_christmas': 'Navidad',
  'beauty_sticker_squid': 'Calamar',
  'beauty_sticker_piggy': 'Cerdito',
  'beauty_sticker_long_cat': 'Gato\nLargo',
  'beauty_sticker_hairhoop': 'Diadema',
  'beauty_sticker_relax_time': 'Relajado',
  'beauty_sticker_cartoon_cat': 'Gato\nDibujo',
  'beauty_sticker_butterfly': 'Mariposa',
  'beauty_sticker_brush': 'Pincel',
  'beauty_sticker_cyber_glass': 'Gafas\nCyber',
  'beauty_sticker_neon_tiara': 'Tiara\nNeón',
  'beauty_sticker_love_glass': 'Gafas\nAmor',
};

const Map<String, String> _arStrings = {
  'beauty_group_beauty': 'جمال',
  'beauty_group_filter': 'فلتر',
  'beauty_group_makeup': 'مكياج',
  'beauty_group_sticker': 'ملصقات',
  'beauty_setting_saved_info': 'تم الحفظ',
  'beauty_setting_reseted_info': 'تم إعادة\nالضبط',
  'beauty_setting_beauty': 'جمال',
  'beauty_setting_save': 'حفظ',
  'beauty_setting_reset': 'إعادة ضبط',
  'beauty_setting_join': 'انضمام',
  'beauty_setting_leave': 'مغادرة',
  'beauty_setting_switch_camera': 'تبديل',
  'beauty_effect_none': 'لا شيء',
  'beauty_effect_enable': 'تفعيل',
  'beauty_effect_disable': 'إيقاف',
  'beauty_effect_reset': 'إعادة ضبط',
  'beauty_effect_smoothness': 'تنعيم',
  'beauty_effect_lightness': 'تبييض',
  'beauty_effect_redness': 'وردي',
  'beauty_effect_contrast_strength': 'وضوح',
  'beauty_effect_sharpness': 'حدة',
  'beauty_effect_eye_pouch': 'هالات\nالعين',
  'beauty_effect_brighten_eye': 'إشراق\nالعين',
  'beauty_effect_whiten_teeth': 'تبييض\nالأسنان',
  'beauty_effect_nasolabial_fold': 'خطوط\nالابتسامة',
  'beauty_effect_temperature': 'درجة اللون',
  'beauty_effect_hue': 'تدرج لوني',
  'beauty_effect_saturation': 'تشبع لوني',
  'beauty_effect_brightness': 'سطوع',
  'beauty_face_shape_face_contour': 'نحف\nالوجه',
  'beauty_face_shape_mandible': 'وجه\nفي',
  'beauty_face_shape_chin': 'الذقن',
  'beauty_face_shape_cheek': 'الفك',
  'beauty_face_shape_cheekbone': 'عظام\nالخد',
  'beauty_face_shape_face_length': 'طول\nالوجه',
  'beauty_face_shape_face_width': 'عرض\nالوجه',
  'beauty_face_shape_fore_head': 'خط\nالشعر',
  'beauty_face_shape_head_scale': 'حجم\nالرأس',
  'beauty_face_shape_nose_width': 'نحف\nالأنف',
  'beauty_face_shape_nose_root': 'جذر\nالأنف',
  'beauty_face_shape_nose_bridge': 'جسر\nالأنف',
  'beauty_face_shape_nose_tip': 'طرف\nالأنف',
  'beauty_face_shape_nose_wing': 'جناح\nالأنف',
  'beauty_face_shape_nose_length': 'طول\nالأنف',
  'beauty_face_shape_nose_general': 'شكل\nالأنف',
  'beauty_face_shape_eye_scale': 'حجم\nالعين',
  'beauty_face_shape_eye_distance': 'مسافة\nالعين',
  'beauty_face_shape_eye_lid': 'جفن\nسفلي',
  'beauty_face_shape_inner_corner': 'زاوية\nداخلية',
  'beauty_face_shape_outer_corner': 'زاوية\nخارجية',
  'beauty_face_shape_eye_position': 'موقع\nالعين',
  'beauty_face_shape_eye_pupils': 'بؤبؤ\nالعين',
  'beauty_face_shape_mouth_smile': 'شفاه\nمبتسمة',
  'beauty_face_shape_mouth_lip': 'سمك\nالشفاه',
  'beauty_face_shape_mouth_scale': 'حجم\nالفم',
  'beauty_face_shape_mouth_position': 'طول\nالشفة',
  'beauty_face_shape_eyebrow_thickness': 'سمك\nالحاجب',
  'beauty_face_shape_eyebrow_position': 'رفع\nالحاجب',
  'beauty_filter_serene': 'هادئ',
  'beauty_filter_urban': 'مدني',
  'beauty_filter_glow': 'متلألئ',
  'beauty_filter_gilt': 'ذهبي',
  'beauty_filter_cream': 'كريمي',
  'beauty_filter_latte': 'لاتيه',
  'beauty_filter_summer': 'صيفي',
  'beauty_filter_daily': 'يومي',
  'beauty_filter_gentleman': 'رجالي',
  'beauty_filter_vanilla': 'فانيليا',
  'beauty_filter_bright': 'مشرق',
  'beauty_filter_peach': 'خوخي',
  'beauty_filter_ink': 'حبري',
  'beauty_filter_film': 'فيلمي',
  'beauty_filter_sunny': 'شمسي',
  'beauty_filter_comic': 'كوميكس',
  'beauty_filter_dreamy': 'حالم',
  'beauty_filter_cotton': 'قطني',
  'beauty_filter_soda': 'صودا',
  'beauty_filter_moonlight': 'ضوء\nالقمر',
  'beauty_filter_white_tea': 'شاي\nأبيض',
  'beauty_filter_tranquil': 'ساكن',
  'beauty_filter_insta_style': 'أسلوب\nانستا',
  'beauty_filter_street': 'شارعي',
  'beauty_filter_puff': 'نفشة',
  'beauty_filter_collection': 'مجموعة',
  'beauty_filter_salty': 'مالح',
  'beauty_filter_texture': 'ملمس',
  'beauty_filter_colorful': 'ملون',
  'beauty_filter_snow': 'ثلجي',
  'beauty_filter_blush': 'احمرار\nالخدود',
  'beauty_filter_nostalgia': 'حنين',
  'beauty_filter_caramel': 'كراميل',
  'beauty_filter_tipsy': 'سكران',
  'beauty_filter_lavender': 'لافندر',
  'beauty_filter_rouge': 'أحمر',
  'beauty_filter_misty': 'ضبابي',
  'beauty_makeup_young': 'شبابي',
  'beauty_makeup_mature': 'ناضج',
  'beauty_makeup_aura': 'هالة',
  'beauty_makeup_natural': 'طبيعي',
  'beauty_makeup_graceful': 'أنيق',
  'beauty_makeup_charm': 'جذاب',
  'beauty_makeup_perky': 'مرح',
  'beauty_makeup_maiden': 'بناتي',
  'beauty_makeup_insight': 'عميق',
  'beauty_makeup_misty': 'ضبابي',
  'beauty_sticker_christmas': 'كريسماس',
  'beauty_sticker_squid': 'حبار',
  'beauty_sticker_piggy': 'خنزير',
  'beauty_sticker_long_cat': 'قطة\nطويلة',
  'beauty_sticker_hairhoop': 'طوق\nوردي',
  'beauty_sticker_relax_time': 'استرخاء',
  'beauty_sticker_cartoon_cat': 'قطة\nكرتون',
  'beauty_sticker_butterfly': 'فراشة',
  'beauty_sticker_brush': 'فرشاة',
  'beauty_sticker_cyber_glass': 'نظارة\nسايبر',
  'beauty_sticker_neon_tiara': 'تاج\nنيون',
  'beauty_sticker_love_glass': 'نظارة\nحب',
};

const Map<String, String> _idStrings = {
  'beauty_group_beauty': 'Kecantikan',
  'beauty_group_filter': 'Filter',
  'beauty_group_makeup': 'Makeup',
  'beauty_group_sticker': 'Stiker',
  'beauty_setting_saved_info': 'Pengaturan\ndisimpan',
  'beauty_setting_reseted_info': 'Pengaturan\ndireset',
  'beauty_setting_beauty': 'Kecantikan',
  'beauty_setting_save': 'Simpan',
  'beauty_setting_reset': 'Reset',
  'beauty_setting_join': 'Gabung',
  'beauty_setting_leave': 'Keluar',
  'beauty_setting_switch_camera': 'Ganti',
  'beauty_effect_none': 'Tidak ada',
  'beauty_effect_enable': 'Aktif',
  'beauty_effect_disable': 'Nonaktif',
  'beauty_effect_reset': 'Reset',
  'beauty_effect_smoothness': 'Halus',
  'beauty_effect_lightness': 'Putih',
  'beauty_effect_redness': 'Merona',
  'beauty_effect_contrast_strength': 'Klaritas',
  'beauty_effect_sharpness': 'Ketajaman',
  'beauty_effect_eye_pouch': 'Lingkar\nMata',
  'beauty_effect_brighten_eye': 'Cerah\nMata',
  'beauty_effect_whiten_teeth': 'Putih\nGigi',
  'beauty_effect_nasolabial_fold': 'Garis\nSenyum',
  'beauty_effect_temperature': 'Suhu',
  'beauty_effect_hue': 'Warna',
  'beauty_effect_saturation': 'Jenis\nWarna',
  'beauty_effect_brightness': 'Kecerahan',
  'beauty_face_shape_face_contour': 'Pipih\nWajah',
  'beauty_face_shape_mandible': 'V\nWajah',
  'beauty_face_shape_chin': 'Dagu',
  'beauty_face_shape_cheek': 'Rahang',
  'beauty_face_shape_cheekbone': 'Tulang\nPipi',
  'beauty_face_shape_face_length': 'Panjang\nWajah',
  'beauty_face_shape_face_width': 'Lebar\nWajah',
  'beauty_face_shape_fore_head': 'Garis\nRambut',
  'beauty_face_shape_head_scale': 'Ukuran\nKepala',
  'beauty_face_shape_nose_width': 'Hidung\nPipih',
  'beauty_face_shape_nose_root': 'Akar\nHidung',
  'beauty_face_shape_nose_bridge': 'Jembatan\nHidung',
  'beauty_face_shape_nose_tip': 'Ujung\nHidung',
  'beauty_face_shape_nose_wing': 'Sayap\nHidung',
  'beauty_face_shape_nose_length': 'Panjang\nHidung',
  'beauty_face_shape_nose_general': 'Ukuran\nHidung',
  'beauty_face_shape_eye_scale': 'Ukuran\nMata',
  'beauty_face_shape_eye_distance': 'Jarak\nMata',
  'beauty_face_shape_eye_lid': 'Kelopak\nBawah',
  'beauty_face_shape_inner_corner': 'Sudut\nDalam',
  'beauty_face_shape_outer_corner': 'Sudut\nLuar',
  'beauty_face_shape_eye_position': 'Posisi\nMata',
  'beauty_face_shape_eye_pupils': 'Murid',
  'beauty_face_shape_mouth_smile': 'Senyum',
  'beauty_face_shape_mouth_lip': 'Tebal\nBibir',
  'beauty_face_shape_mouth_scale': 'Ukuran\nMulut',
  'beauty_face_shape_mouth_position': 'Filtra',
  'beauty_face_shape_eyebrow_thickness': 'Tebal\nAlis',
  'beauty_face_shape_eyebrow_position': 'Angkat\nAlis',
  'beauty_filter_serene': 'Tenang',
  'beauty_filter_urban': 'Perkotaan',
  'beauty_filter_glow': 'Bercahaya',
  'beauty_filter_gilt': 'Emas',
  'beauty_filter_cream': 'Krim',
  'beauty_filter_latte': 'Latte',
  'beauty_filter_summer': 'Musim\nPanas',
  'beauty_filter_daily': 'Sehari-hari',
  'beauty_filter_gentleman': 'Beradab',
  'beauty_filter_vanilla': 'Vanila',
  'beauty_filter_bright': 'Cerah',
  'beauty_filter_peach': 'Persik',
  'beauty_filter_ink': 'Tinta',
  'beauty_filter_film': 'Film',
  'beauty_filter_sunny': 'Cerah\nMatahari',
  'beauty_filter_comic': 'Komik',
  'beauty_filter_dreamy': 'Mimpi',
  'beauty_filter_cotton': 'Katun',
  'beauty_filter_soda': 'Soda',
  'beauty_filter_moonlight': 'Cahaya\nBulan',
  'beauty_filter_white_tea': 'Teh\nPutih',
  'beauty_filter_tranquil': 'Diam',
  'beauty_filter_insta_style': 'Gaya\nIns',
  'beauty_filter_street': 'Jalan',
  'beauty_filter_puff': 'Kue',
  'beauty_filter_collection': 'Koleksi',
  'beauty_filter_salty': 'Asin',
  'beauty_filter_texture': 'Tekstur',
  'beauty_filter_colorful': 'Warna',
  'beauty_filter_snow': 'Salju',
  'beauty_filter_blush': 'Perona',
  'beauty_filter_nostalgia': 'Nostalgia',
  'beauty_filter_caramel': 'Karamel',
  'beauty_filter_tipsy': 'Mabuk',
  'beauty_filter_lavender': 'Lavender',
  'beauty_filter_rouge': 'Merah',
  'beauty_filter_misty': 'Kabut',
  'beauty_makeup_young': 'Muda',
  'beauty_makeup_mature': 'Dewasa',
  'beauty_makeup_aura': 'Aura',
  'beauty_makeup_natural': 'Alami',
  'beauty_makeup_graceful': 'Anggun',
  'beauty_makeup_charm': 'Pesona',
  'beauty_makeup_perky': 'Ceria',
  'beauty_makeup_maiden': 'Gadis',
  'beauty_makeup_insight': 'Dalam',
  'beauty_makeup_misty': 'Kabut',
  'beauty_sticker_christmas': 'Natal',
  'beauty_sticker_squid': 'Cumi',
  'beauty_sticker_piggy': 'Babi',
  'beauty_sticker_long_cat': 'Kucing\nEkor',
  'beauty_sticker_hairhoop': 'Bando\nPink',
  'beauty_sticker_relax_time': 'Santai',
  'beauty_sticker_cartoon_cat': 'Kucing\nKartun',
  'beauty_sticker_butterfly': 'Kupu-kupu',
  'beauty_sticker_brush': 'Waktu\nCat',
  'beauty_sticker_cyber_glass': 'Kacamata\nCyber',
  'beauty_sticker_neon_tiara': 'Mahkota\nNeon',
  'beauty_sticker_love_glass': 'Kacamata\nCinta',
};

const Map<String, String> _enStrings = {
  'beauty_group_beauty': 'Beauty',
  'beauty_group_filter': 'Filter',
  'beauty_group_makeup': 'Makeup',
  'beauty_group_sticker': 'Sticker',
  'beauty_setting_saved_info': 'Beauty settings saved',
  'beauty_setting_reseted_info': 'Beauty settings reseted',
  'beauty_setting_beauty': 'Beauty',
  'beauty_setting_save': 'Save',
  'beauty_setting_reset': 'Reset',
  'beauty_setting_join': 'Join',
  'beauty_setting_leave': 'Leave',
  'beauty_setting_switch_camera': 'Switch',
  'beauty_effect_none': 'None',
  'beauty_effect_enable': 'Enable',
  'beauty_effect_disable': 'Disable',
  'beauty_effect_reset': 'Reset',
  'beauty_effect_smoothness': 'Smooth',
  'beauty_effect_lightness': 'Whiten',
  'beauty_effect_redness': 'Rosy',
  'beauty_effect_contrast_strength': 'Clarity',
  'beauty_effect_sharpness': 'Sharpen',
  'beauty_effect_eye_pouch': 'Dark\nCircles',
  'beauty_effect_brighten_eye': 'Eye\nBrighten',
  'beauty_effect_whiten_teeth': 'Teeth\nWhitening',
  'beauty_effect_nasolabial_fold': 'Smile\nLines',
  'beauty_effect_temperature': 'Temp',
  'beauty_effect_hue': 'Tint',
  'beauty_effect_saturation': 'Saturation',
  'beauty_effect_brightness': 'Brightness',
  'beauty_face_shape_face_contour': 'Face\nSlim',
  'beauty_face_shape_mandible': 'V-Face',
  'beauty_face_shape_chin': 'Chin',
  'beauty_face_shape_cheek': 'Jaw',
  'beauty_face_shape_cheekbone': 'Cheek\nBones',
  'beauty_face_shape_face_length': 'Face\nLength',
  'beauty_face_shape_face_width': 'Face\nWidth',
  'beauty_face_shape_fore_head': 'Hairline',
  'beauty_face_shape_head_scale': 'Head\nSize',
  'beauty_face_shape_nose_width': 'Nose\nSlim',
  'beauty_face_shape_nose_root': 'Radix',
  'beauty_face_shape_nose_bridge': 'Nose\nBridge',
  'beauty_face_shape_nose_tip': 'Nose\nTip',
  'beauty_face_shape_nose_wing': 'Nose\nWing',
  'beauty_face_shape_nose_length': 'Nose\nLength',
  'beauty_face_shape_nose_general': 'Nose\nSize',
  'beauty_face_shape_eye_scale': 'Eye\nSize',
  'beauty_face_shape_eye_distance': 'Eye\nDist',
  'beauty_face_shape_eye_lid': 'Lower\nEyelid',
  'beauty_face_shape_inner_corner': 'Inner\nCorner',
  'beauty_face_shape_outer_corner': 'Outer\nCorner',
  'beauty_face_shape_eye_position': 'Eye\nPos',
  'beauty_face_shape_eye_pupils': 'Pupil',
  'beauty_face_shape_mouth_smile': 'Smile',
  'beauty_face_shape_mouth_lip': 'Lip\nThick',
  'beauty_face_shape_mouth_scale': 'Mouth\nSize',
  'beauty_face_shape_mouth_position': 'Philtrum',
  'beauty_face_shape_eyebrow_thickness': 'Brow\nThick',
  'beauty_face_shape_eyebrow_position': 'Brow\nLift',
  'beauty_filter_serene': 'Serene',
  'beauty_filter_urban': 'Urban',
  'beauty_filter_glow': 'Glow',
  'beauty_filter_gilt': 'Gilt',
  'beauty_filter_cream': 'Cream',
  'beauty_filter_latte': 'Latte',
  'beauty_filter_summer': 'Summer',
  'beauty_filter_daily': 'Daily',
  'beauty_filter_gentleman': 'Gentleman',
  'beauty_filter_vanilla': 'Vanilla',
  'beauty_filter_bright': 'Bright',
  'beauty_filter_peach': 'Peach',
  'beauty_filter_ink': 'Ink',
  'beauty_filter_film': 'Film',
  'beauty_filter_sunny': 'Sunny',
  'beauty_filter_comic': 'Comic',
  'beauty_filter_dreamy': 'Dreamy',
  'beauty_filter_cotton': 'Cotton',
  'beauty_filter_soda': 'Soda',
  'beauty_filter_moonlight': 'Moonlight',
  'beauty_filter_white_tea': 'White\nTea',
  'beauty_filter_tranquil': 'Tranquil',
  'beauty_filter_insta_style': 'Ins',
  'beauty_filter_street': 'Street',
  'beauty_filter_puff': 'Puff',
  'beauty_filter_collection': 'Collection',
  'beauty_filter_salty': 'Salty',
  'beauty_filter_texture': 'Texture',
  'beauty_filter_colorful': 'Colorful',
  'beauty_filter_snow': 'Snow',
  'beauty_filter_blush': 'Blush',
  'beauty_filter_nostalgia': 'Nostalgia',
  'beauty_filter_caramel': 'Caramel',
  'beauty_filter_tipsy': 'Tipsy',
  'beauty_filter_lavender': 'Lavender',
  'beauty_filter_rouge': 'Rouge',
  'beauty_filter_misty': 'Misty',
  'beauty_makeup_young': 'Young',
  'beauty_makeup_mature': 'Mature',
  'beauty_makeup_aura': 'Aura',
  'beauty_makeup_natural': 'Natural',
  'beauty_makeup_graceful': 'Graceful',
  'beauty_makeup_charm': 'Charm',
  'beauty_makeup_perky': 'Perky',
  'beauty_makeup_maiden': 'Maiden',
  'beauty_makeup_insight': 'Insight',
  'beauty_makeup_misty': 'Misty',
  'beauty_sticker_christmas': 'Christmas',
  'beauty_sticker_squid': 'Squid',
  'beauty_sticker_piggy': 'Piggy',
  'beauty_sticker_long_cat': 'Long Cat',
  'beauty_sticker_hairhoop': 'Hairhoop',
  'beauty_sticker_relax_time': 'Relax',
  'beauty_sticker_cartoon_cat': 'Cartoon Cat',
  'beauty_sticker_butterfly': 'Butterfly',
  'beauty_sticker_brush': 'Brush',
  'beauty_sticker_cyber_glass': 'Cyber Glass',
  'beauty_sticker_neon_tiara': 'Neon Tiara',
  'beauty_sticker_love_glass': 'Love Glass',
};

class BeautyLocalizer {
  BeautyLocalizer._();

  static String _lang = 'en';

  static String get lang => _lang;

  static void setLang(String lang) {
    _lang = lang;
  }
}

String beautyLocalized(String key) {
  final lang = LinkjoyIOSister.getLanguageCode();
  final Map<String, String> map;

  if (lang == 'vi') {
    map = _viStrings;
  } else if (lang == 'pt') {
    map = _ptStrings;
  } else if (lang == 'hi') {
    map = _hiStrings;
  } else if (lang == 'es') {
    map = _esStrings;
  } else if (lang == 'ar') {
    map = _arStrings;
  } else if (lang == 'id') {
    map = _idStrings;
  } else {
    map = _enStrings;
  }
  return map[key] ?? _enStrings[key] ?? key;
}
